on: [push]

jobs:
  quokka_analysis_job:
    runs-on: ubuntu-latest
    name: Submit app to Quokka Portal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Quokka Analysis Submission
        uses: ./ # Uses an action in the root directory
        id: appSubmit
        with:
          path-to-file: "app/build/outputs/apk/prod/debug/app-prod-debug.apk"
          platform: "android"
          apiKey: ${{ secrets.QMAST_API_KEY }}
